Create sbom-github.md
chains-project/chains-project.github.io pull request #21
Opened 2023-06-13 13:35 UTC by MartinWitt

2023-06-13 13:36 UTC, MartinWitt commented
@monperrus here is the post about SBOMs for github releases.

2023-06-13 13:42 UTC, algomaster99 requested changes
Looks good to me!  Suggested a few changes.

2023-06-13 13:42 UTC, algomaster99 commented on README.md
> +- [SBOMs for you GitHub Releases](sbom-github.md)
```suggestion
- [SBOMs for your GitHub Releases](sbom-github.md)
```

2023-06-13 13:42 UTC, algomaster99 commented on sbom-github.md
> +2. Add the bom.xml to your release script.
```suggestion
2. Add the bom.xml and bom.json to your release script.
```

2023-06-14 11:27 UTC, monperrus commented on sbom-github.md
> +It provides a detailed list of all the open-source and third-party components used in a software product, their versions and any known vulnerabilities.
motivate "SBOM in registries", give concrete use cases and advantages

2023-09-08 05:16 UTC, merged